version: "3.5"
services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.1.0
    restart: always
    container_name: kafka1
    networks:
      - backend
    ports:
      - 9092:9092
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.2.241
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka:2.12-2.1.0
    restart: always
    container_name: kafka2
    networks:
      - backend
    ports:
      - 9093:9092
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.2.241
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: wurstmeister/kafka:2.12-2.1.0
    restart: always
    container_name: kafka3
    networks:
      - backend
    ports:
      - 9094:9092
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.2.241
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_CREATE_TOPICS: "log:3:3"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    name: backend
    external: true
