version: "3.7"

services:
  redis:
    image: "redis:3.2-alpine"
    restart: "always"
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend
    ports:
      - 6379:6379
    volumes:
      - ../../config/redis:/usr/local/etc/redis
      - redis:/data

networks:
  backend:
    name: backend
    external: true

volumes:
  redis:
