version: "3.7"

services:
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitor
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitor
    volumes:
      - grafana:/var/lib/grafana

networks:
  monitor:
    name: monitor

volumes:
  influxdb:
  grafana:
