version: "3.7"

services:
  database:
    image: mysql:5.7.25
    container_name: mysql
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    env_file:
      - ../../config/mysql/mysql.env
    volumes:
      - ../../config/mysql:/etc/mysql/conf.d
      - mysql:/var/lib/mysql

networks:
  backend:
    name: backend
    external: true

volumes:
  mysql:
